# Generated by Django 3.2.7 on 2021-09-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_mascotas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascotas',
        ),
    ]
